- Source/Routing and Faulting/Routing and Faulting Custom Device.lvproj
- Source/SLSC Switch/SLSC Switch Custom Device.lvproj
There is a [JKI VI Tester bug](https://github.com/JKISoftware/JKI-VI-Tester/issues/5) where tests cannot be run from the UI if PPLs contain lvlibs. The `SLSCSwitchMessagingLibrary.lvllipb` contains `SLSC Switch.lvlib`, which means we hit this bug.
This change lets us run tests from the UI and ensures dependent PPLs are built to the proper location.
We want to run the VI Tester from the UI as developers to validate changes before committing pull requests.
Built locally to ensure same file output structure.
Built with VIs using the PPLs to verify they are copied to the correct location in the build output.
> Remove dependent PPLs from project

- build.toml
- control_routing_faulting
- control_slsc_switch
Builds a separate `.nipkg` file for the Routing and Faulting and the SLSC Switch custom devices.
The custom devices need to install to separate locations and should be installed through different packages.
**Note**: Ultimately, there should be _RECOMMENDS_ and _REQUIRES_ relationships between the packages, but this is a first pass at getting the packages building so they can be pulled into a feed.
[Built dev branch](http://coordinator/job/VeriStand/job/ni/job/niveristand-routing-and-faulting-custom-device/job/dev%252Fmulti-pkg/2/). Verified each package contains only the correct custom device in the correct install location.
Build output:
> Build nipkg for each custom device

- build.toml
Installs the nipkg files to the correct folder structure.
Currently, everything gets installed to a top-level folder, which sprinkles files everywhere.
None. Need a release build to validate.
> Install nipkgs to correct folders

- control_routing_faulting
- control_slsc_switch
Names the nipkg files according to convention and to be consistent with other custom devices.
Consistency.
None
> Fix package names to match convention

- Source/Routing and Faulting/Routing and Faulting Custom Device.lvproj
- Source/SLSC Switch/SLSC Switch Custom Device.lvproj
- build.toml
- control_routing_faulting_scripting
- control_slsc_switch_scripting
Add initial package building for installing the scripting APIs. 
Add two new packages, one per custom device, that install the scripting APIs to vi.lib. The scripting APIs are installed as source, instead of LLBs.
The exact structure of the scripting APIs is not determined; we will want to fix a dependency inversion in the Routing and Faulting shared library that is pulling in the System Explorer library. This is currently causing the installed files to be nested inside another directory.
We eventually want to install palette and example files; this is the first step.
Built the packages on a dev branch and confirmed they install into vi.lib.
`\\nirvana\measurements\VeriStandAddons\routing_and_faulting_custom_device\ni\export\dev\lv_integration\Build 7\2017\installer`
> Build packages for scripting APIs

- Source/Routing and Faulting/Custom Device Routing and Faulting.xml
- Renames `Aliases` section to `Endpoint Aliases` to match the string in the scripting API.
-  Prevents renaming and deletion of `Endpoint Aliases` and `Routing Channels` sections.
Strings should match between the scripting API and users should not be able to delete these sections.
Built and made sure names are correct when adding the custom device and sections cannot be renamed or deleted.
> Rename aliases and disallow renaming/deletion

- build.toml
Install examples to `NI VeriStand Custom Devices`.
This makes the directory appear adjacent to the existing VeriStand examples.
Requested by @jashnani.
None.
> Install examples to `NI VeriStand Custom Devices`

- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF.nivssdf
- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF_Diff_Resource.nivssdf
- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF_Initial_States.nivssdf
- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF_Invalid_Switch_Resource.nivssdf
- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF_No_Routing_Channels.nivssdf
- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF_Rich_States.nivssdf
- Source/Routing and Faulting/Tests/System/Assets/Switch_and_RaF_Rich_States_Aliases.nivssdf
This appears to fix the tests when the SLSC chassis is not in the local configuration.
The tests are currently failing.
These same changes were made during a test run, and fixed the failing tests.
> Set SLSC chassis type to IP address, from hostname

- Source/Routing and Faulting/Routing and Faulting Custom Device.lvproj
- Source/SLSC Switch/SLSC Switch Custom Device.lvproj
Fixes #126 
Renames the shared `Routing and Faulting Hardware API.lvlib` and `UI Common.lvlib` during both the Routing and Faulting and SLSC Switch custom device builds. This prevents pages from separate libraries trying to load the same dependencies from the previous page's library.
Renaming both libraries in anticipation of potentially adding other custom device's that would need to implement the `Routing and Faulting Hardware API.lvlib`. With only renaming one, other custom devices could hit the same problem when moving between the different hardware custom devices.
There is no good explanation for why the pages are broken when they are selected. It's also a simple fix.
Manual testing of page loading between all pages in the two custom devices.
> Fix shared library name collisions breaking pages

- Source/Routing and Faulting/Routing and Faulting Custom Device.lvproj
- Source/Routing and Faulting/Scripting/Routing and Faulting Scripting.lvlib
- Source/SLSC Switch/SLSC Switch Custom Device.lvproj
- Source/SLSC Switch/Scripting/SLSC Switch Scripting.lvlib
Manually bundles the Import/Export and Advanced System Definition libraries used by the scripting APIs into LLBs that will be distributed with the scripting APIs. To avoid name conflicts with other copies of these libraries, I am prefixing their names with e.g. "Routing_and_Faulting_Scripting_Dependencies_".
Currently we expect people to have installed these dependencies via VI packages. Since nipkgs can't install VI packages, we want to redistribute these. 
Hand testing that the scripting APIs appear to resolve dependencies correctly when built.
> Build dependencies for scripting APIs into LLBs

- control_examples
- control_routing_faulting
- control_routing_faulting_scripting
- control_slsc_switch
- control_slsc_switch_scripting
Add dependencies on VeriStand and LabVIEW to the nipkgs.
This prevents installing the packages in environments where they can't be used.
None, currently waiting on a build to test.
> Add nipkg dependencies on VeriStand and LabVIEW

- Source/Routing and Faulting/Routing and Faulting Custom Device.lvproj
- Source/SLSC Switch/SLSC Switch Custom Device.lvproj
- Source/Scripting Examples/Scripting Examples.lvproj
Remove compiled code from the scripting APIs and examples during build. This had previously defaulted to preserving the compiled code.
Fixes #178.
Built the scripting packages and examples.
> Remove compiled code for scripting APIs and examples during build

- control_custom_device_labview_support_common
- control_examples
- control_routing_faulting
- control_routing_faulting_scripting
- control_slsc_switch
- control_slsc_switch_scripting
Change package architecture to windows_x64, to align with the VeriStand 2019 and newer package architecture.
VeriStand 2019 and newer are windows_x64 packages, so having the custom device be windows_all is a bit nonsensical (and is causing warnings to be thrown by internal tooling). Changing the package to windows_x64 prevents installation of the custom devices via .nipkg on 32-bit Windows for VeriStand 2018 and older, but this is a niche use case and workarounds are available.
None.
> Mark architecture as windows_x64

- Source/Routing and Faulting/Scripting/Tests/System/targets.ini
TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/master/CONTRIBUTING.md).
It add a target.ini file for the Deploy Scripted System Definition test
Deploy Scripted System Definition is a system test that needs this file.
More than you can imagine = finally got the test to run (and pass) on my VM.
> Adding target.ini file

- Source/SLSC Switch/Scripting/Tests/System/targets.ini
This does the same thing as #194, but for the SLSC Switch scripting system test:
Add a target.ini file for the Deploy Scripted System Definition test
This will execute the auto-test as a system test, as it needs PXI hardware online.
None.
> Add targets.ini to SLSC Switch scripting system tests

- build.toml
Enables build notifications to Microsoft Teams on build failures/fixes.
We want to know when builds fail.
None
> Add build notification

- Source/SLSC Switch/Scripting/Tests/System/Assets/Base with 1 SLSC Switch CD.nivssdf
- Source/SLSC Switch/Scripting/Tests/System/Assets/config.ini
Use the SLSC chassis IP address, rather than the hostname.
Remove the override from the config file because it wasn't working due to the test structure.
This fixes a test. Network changes have made the chassis unreachable by hostname.
Confirmed test passes on the ATS with this change.
> Use SLSC IP address instead of hostname in scripting test

- Source/NI-SWITCH/NI-SWITCH Custom Device.lvproj
Change the build output directory for the NI-SWITCH PharLap specification.
The custom device currently cannot deploy to PharLap, and reports an error in System Explorer.
Inspecting PR build output.
> Fix NI-SWITCH PharLap builds not building to the correct place

- Source/NI-SWITCH/Help/HTML Help Source/Main.htm
Document the `Resource` and `Topology` fields for the main page of the NI-SWITCH custom device.
These fields currently are undocumented, which can be confusing.
> Document NI-SWITCH main page configuration options in CHM

- Includes/README.md
- README.md
Update developers and users to the need to install a compatible version of NI-SWITCH to use all of Routing and Faulting
Update developers to add `NISWITCHMessaging.lvlibp` to the "Includes" directory
Keep docs up to date
None
> Add NI-SWITCH dependencies to Readmes

- Source/NI-SWITCH/NI-SWITCH Custom Device.lvproj
- Source/Routing and Faulting/Routing and Faulting Custom Device.lvproj
- Source/SLSC Switch/SLSC Switch Custom Device.lvproj
Don't modify project libraries during build.
Since the custom devices in this repo share source dependencies, but don't necessarily all use the same set of VIs from those dependencies, modifying the libraries during build can result in run-time failures.
This is a partial, speculative fix for some issues @Karl-G1 saw in System Explorer when switching between custom devices. 
Attempted to reproduce the bug after rebuilding SLSC Switch and NI-SWITCH locally but could not.
> Don't modify project libraries during build

- build.toml
Fix a copy-paste error for the NI-SWITCH scripting error location.
The NI-SWITCH scripting package currently doesn't install errors to the same location as the other scripting packages. Found on a call with @douglasnorman.
Relying on PR build.
> NI-SWITCH scripting errors go to the same place as the other CDs

- control_routing_faulting_scripting
Update `ni-routing-and-faulting-veristand-{veristand_version}-labview-support` to recommend the new scripting example packages.
The current recommendation is broken.
N/A
> Fix recommendation

- Source/NI-SWITCH/Custom Device NI-SWITCH.xml
- Source/Routing and Faulting/Custom Device Routing and Faulting.xml
Make the custom devices appear under the "NI" menu item, rather than "National Instruments".
Branding update.
N/A
> Parent custom devices under NI in menu

- build.toml
- control_custom_device_labview_support_common
- control_ni_switch
- control_ni_switch_examples
- control_ni_switch_scripting
- control_routing_faulting
- control_routing_faulting_scripting
- control_slsc_switch
- control_slsc_switch_examples
- control_slsc_switch_scripting
Update package installation paths and dependencies to accommodate different LabVIEW bitnesses.
We are using LabVIEW 2021 64-bit.
Inspected PR-built packages.
> Install to bitness-specific locations

- control_ni_switch
- control_ni_switch_examples
- control_ni_switch_scripting
- control_routing_faulting
- control_routing_faulting_scripting
- control_slsc_switch
- control_slsc_switch_examples
- control_slsc_switch_scripting
Use quarterly display version, and upgrade `ni-veristand-{veristand_version}-custom-device-labview-support-common` dependency to `23.0.0`.
We need the newer `ni-veristand-{veristand_version}-custom-device-labview-support-common` dependency as there is not a `21.0.0` version supporting LabVIEW 2023.
PR build.
> Use quarterly display version, 23.0.0 common package

- control_ni_switch
- control_ni_switch_scripting
- control_slsc_switch
- control_slsc_switch_scripting
Fix LabVIEW driver support package dependencies for packages which support LabVIEW 2023 Q1 in a version agnostic way.
Uptakes changes from https://github.com/ni/niveristand-custom-device-build-tools/pull/138.
This is needed to make the 2023 Q1 support installable.
PR build.
> Handle drivers with version-independent LabVIEW support

- azure-pipelines.yml
Changes pipeline completion trigger to only activate when changes are made to main.
Currently pipelines are being triggered off of all builds, we should just trigger off of CI builds when changes are merged to main.
Tested with imitation-cd beforehand, requires a CI build or manual build to activate pipeline completion trigger.
> only trigger from cd message library CI builds

- azure-pipelines.yml
pack parameter was removed in build tools with latest updates.  build output location also fixed, that was inadvertently altered at some point.
build won't run with invalid parameters.  Archive step will fail with current set up since Built is the wrong location.
build runs
> remove pack parameter

- control_ni_switch_scripting
- control_routing_faulting_scripting
- control_slsc_switch_scripting
Bump a hard-coded dependency from 23.0 to 24.0.
Needed for the feed build to pass.
PR build.
> Bump custom device LabVIEW support package dependency

- control_ni_switch_examples
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited …
> Add localization text in niveristand-routing-and-faulting-custom-device-ni-switch-LabVIEW-Example control page

- control_slsc_switch_scripting
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited …
> Add localisation text in niveristand-routing-faulting-custom-device-LabVIEW-Support   

- control_slsc_switch_examples
- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-routing-and-faulting-custom-device/blob/main/CONTRIBUTING.md).
Taken reference from VeriStand control page …
> Add localization text in niveristand-routing-and-faulting-cd-slsc-switch-LabVIEW-examples control page

- control_routing_faulting_scripting
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited …
> Add localization text in niveristand-routing-and-faulting-custom-device-LabVIEW-Support

- control_routing_faulting
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited niveristand-routing-and-faulting …
> Add localization text in niveristand-routing-and-faulting-cd control page

- control_slsc_switch
Taken reference from VeriStand control page (‪\argo\ni\nipkg\pool\ni-v\ni-veristand-2024\24.0.0\24.0.0.49451-0+f299\ni-veristand-2024_24.0.0.49451-0+f299_windows_x64.nipkg.control) and edited …
> Add localization text in niveristand-routing-and-faulting-cd-slsc-switch control page
